experiment:
  dataset: yaudit_svd
  data_config:
#    strategy: dataset
#    dataset_path: ../data/base_data/base_data_1_norec_1_rec_5_watched.tsv
    strategy: hierarchy
    root_folder: data/splitting/svd
#  splitting:
#    save_on_disk: True
#    save_folder: ../data/splitting/svd
#    test_splitting:
#      strategy: random_cross_validation
#      folds: 10
  top_k: 10
  evaluation:
    simple_metrics: [ nDCG,Precision,Recall,MRR ]  # NS, SERP-MS
    relevance_threshold: 1
    # paired_ttest: True
    # wilcoxon_test: True
  models:
    SVDpp:
      meta:
        save_recs: True
      epochs: 10
      batch_size: [64, 128]
      factors: [100, 500, 1000]
      lr: 0.001
      reg_w: .3
      reg_b: .1
#    FunkSVD:
#      meta:
#        save_recs: True
#      epochs: 10
#      batch_size: [64, 128]
#      factors: [100, 500, 1000]
#      lr: 0.0003
#      reg_w: .1
#      reg_b: .001
  print_results_as_triplets: True
